# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b642d66b5ade70e21740ad5b73eafe87e34ea2952dd2547fa7da2a8a297bda016c790bf7d869bf73b68d275954b2ad3a9a851ca82a7eff4eec36c229797f626

test:
  secret_key_base: 8921efedd8466c52bc7cfab78a24ce3bc8f627c8868fc10d4f720e7450964fc564b8c522ba4ce8c82e180b876df5af38547256cc1ddfc03329089dcc2f184d14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
